baseURL = 'http://a7vicky.github.io/blog/'
languageCode = 'en-us'
title = "Abhishek's Blog"
theme = "harbor"

[Author]
  name = "Hugo Author"

[outputs]
  section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3

[[params.nav]]
  identifier = "categories"
  name = "Category"
  icon = "fas fa-folder-open fa-lg"
  url = "categories"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "search"
  weight = 3

[[params.nav]]
  identifier = "archives"
  name = "Archives"
  icon = "fas fa-archive fa-lg"
  url = "archives"
  weight = 3


[params]
  author = "Abhishek Vicky"
  description = "All technical stuff I do as a SRE."
  avatar = "vicky.jpg"

  [[params.social]]
    name = "GitHub"
    link = "https://github.com/a7vicky"

  [[params.social]]
    name = "Twitter"
    link = "https://twitter.com/vicky18dec"

  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/a7vicky"
